### ISSUE TITLE
Add use case to README.MD 

### ISSUE THREAD

**Issue by ghost** [qrohlf/GifHub#9]
Add to README.md some instructions about how to use your web extension? What need I to do use it?
```
Just put url to markdown like: https://i.imgur.com/123.mp4
Or how?
```

**Comment by qrohlf** [comment]
https://github.com/qrohlf/GifHub#usage

you just need to paste the link to a supported .gifv or .webm file into any github discussion. The video will show up in Preview and when you submit the comment.
